name: Update French localization file
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 */4 * * *' # every 4 hours

permissions:
  contents: write
  pull-requests: write

jobs:
  prepare:
    name: Prepare
    if: github.repository == 'Dymerz/StarCitizen-Localization'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout current repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      uses: chill-viking/npm-ci@v1.2.0
      with:
        working_directory: tools/ini-utils

    - name: Build ini-utils
      working-directory: tools/ini-utils
      run: npm run build

    - uses: actions/upload-artifact@v3
      with:
        name: ini-utils
        if-no-files-found: error
        path: |
          tools/ini-utils
          !tools/ini-utils/examples/
          !tools/ini-utils/src/

  merge-and-pr:
    name: Merge and create Pull Request
    if: github.repository == 'Dymerz/StarCitizen-Localization'
    runs-on: ubuntu-latest
    needs: prepare

    steps:
    - uses: actions/download-artifact@v3
      with:
        name: ini-utils
        path: tools/ini-utils

    - name: Download global.ini from 'SPEED0U/StarCitizenTranslations' - AI translated
      run: |
        curl -o global.ini -L "https://raw.githubusercontent.com/SPEED0U/StarCitizenTranslations/main/french_(france)/global.ini"
        mv global.ini ai.ini

    - name: Download global.ini from 'traduction.circuspes.fr' - Human translated
      run: |
        curl -o global.ini -L "https://traduction.circuspes.fr/download/global.ini"
        mv global.ini human.ini

    - name: Merge INI files
      run: node ./tools/ini-utils/dist/src/index.js merge "$GITHUB_WORKSPACE/data/Localization/english/global.ini" "$GITHUB_WORKSPACE/human.ini" "$GITHUB_WORKSPACE/ai.ini" "$GITHUB_WORKSPACE/data/Localization/french_(france)/global.ini"

    - name: Create Pull Request
      if: github.ref == 'refs/heads/main'
      uses: peter-evans/create-pull-request@v5
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SCOPED_TOKEN }}
      with:
        add-paths: data/Localization/french_(france)/global.ini
        commit-message: Update French localization 🇫🇷
        branch: feature/update-french
        delete-branch: true
        title: Update French localization 🇫🇷
        labels: french
        assignees: Dymerz
